name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - &checkout-step
        name: (prepare) Checkout code
        uses: actions/checkout@v4

      - &setup-pnpm-step
        name: (prepare) Setup pnpm
        uses: pnpm/action-setup@v3

      - &setup-node-step
        name: (prepare) Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - &install-dependencies-step
        name: (prepare) Install dependencies
        run: pnpm install --frozen-lockfile

      - name: (main) Run tests
        run: pnpm test

  e2e-test:
    name: End-to-End Test
    runs-on: ubuntu-latest
    steps:
      - *checkout-step
      - *setup-pnpm-step
      - *setup-node-step
      - *install-dependencies-step

      - name: (main) Run end-to-end tests
        run: pnpm run test:e2e

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - *checkout-step
      - *setup-pnpm-step
      - *setup-node-step
      - *install-dependencies-step

      - name: (main) Run linter
        run: pnpm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - *checkout-step
      - *setup-pnpm-step
      - *setup-node-step
      - *install-dependencies-step

      - &build-step
        name: (main) Build project
        run: pnpm run build
