name: Misc - Make Versioning PR

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  versioning:
    name: Misc - Versioning
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: (prepare) Checkout code
        uses: actions/checkout@v6
      
      - name: (prepare) Setup pnpm
        uses: pnpm/action-setup@v3

      - name: (prepare) Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: (prepare) Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Versioning Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
